# ─────────────────────────────────────────────────────────────
# 1. TODO APP — Deployment
# ─────────────────────────────────────────────────────────────
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: sauravnirala/nodejs-todo-devops-project:v1
          ports:
            - containerPort: 3000

---
# ─────────────────────────────────────────────────────────────
# 2. TODO APP — Service
# ─────────────────────────────────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  namespace: myapp
spec:
  selector:
    app: todo-app
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
---
# ─────────────────────────────────────────────────────────────
# 3. TIC TAC TOE — Deployment
# ─────────────────────────────────────────────────────────────
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictactoe
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tictactoe
  template:
    metadata:
      labels:
        app: tictactoe
    spec:
      containers:
        - name: tictactoe
          image: sauravnirala/tictactoe-app:v1
          ports:
            - containerPort: 8081

---
# ─────────────────────────────────────────────────────────────
# 4. TIC TAC TOE — Service
# ─────────────────────────────────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: tictactoe-service
  namespace: myapp
spec:
  selector:
    app: tictactoe
  ports:
    - port: 80
      targetPort: 8081
  type: ClusterIP
